demonyms = {'Afghanistan': 'Afghan',
 'Albania': 'Albanian',
 'Algeria': 'Algerian',
 'Andorra': 'Andorran',
 'Angola': 'Angolan',
 'Antigua and Barbuda': 'Antigua and Barbuda',
 'Argentina': 'Argentine',
 'Armenia': 'Armenian',
 'Australia': 'Australian',
 'Austria': 'Austrian',
 'Azerbaijan': 'Azerbaijani',
 'Bahamas': 'Bahamian',
 'Bahrain': 'Bahraini',
 'Bangladesh': 'Bangladeshi',
 'Barbados': 'Barbadian',
 'Belarus': 'Belarusian',
 'Belgium': 'Belgian',
 'Belize': 'Belizean',
 'Benin': 'Beninese',
 'Bhutan': 'Bhutanese',
 'Bolivia': 'Bolivian',
 'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
 'Botswana': 'Botswana',
 'Brazil': 'Brazilian',
 'Brunei': 'Bruneian',
 'Bulgaria': 'Bulgarian',
 'Burkina Faso': 'Burkinabe',
 'Myanmar': 'Myanmar',
 'Burundi': 'Burundian',
 'Cape Verde': 'Cape Verdean',
 'Cambodia': 'Cambodian',
 'Cameroon': 'Cameroonian',
 'Canada': 'Canadian',
 'Central African Republic': 'Central African Republic',
 'Chad': 'Chadian',
 'Chile': 'Chilean',
 "China": 'Chinese',
 'Colombia': 'Colombian',
 'Comoros': 'Comorian',
 'Democratic Republic of the Congo': 'Democratic Republic of the Congo',
 'Republic of the Congo': 'Republic of the Congo',
 'Costa Rica': 'Costa Rican',
 "Côte d'Ivoire": 'Ivorian',
 'Croatia': 'Croatian',
 'Cuba': 'Cuban',
 'Cyprus': 'Cypriot',
 'Czech Republic': 'Czech',
 'Denmark': 'Danish',
 'Djibouti': 'Djiboutian',
 'Dominica': 'Dominica',
 'Dominican Republic': 'Dominican Republic',
 'Timor-Leste': 'East Timorese',
 'Ecuador': 'Ecuadorian',
 'Egypt': 'Egyptian',
 'El Salvador': 'El Salvador',
 'Equatorial Guinea': 'Equatorial Guinean',
 'Eritrea': 'Eritrean',
 'Estonia': 'Estonian',
 'Ethiopia': 'Ethiopian',
 'Fiji': 'Fijian',
 'Finland': 'Finnish',
 'France': 'French',
 'Gabon': 'Gabonese',
 'Gambia': 'Gambian',
 'Georgia': 'Georgian',
 'Germany': 'German',
 'Ghana': 'Ghanaian',
 'Gibraltar': 'Gibraltar',
 'Greece': 'Greek',
 'Grenada': 'Grenadian',
 'Guatemala': 'Guatemalan',
 'Guinea': 'Guinean',
 'Guinea-Bissau': 'Guinea-Bissauan',
 'Guyana': 'Guyanese',
 'Haiti': 'Haitian',
 'Honduras': 'Honduran',
 'Hungary': 'Hungarian',
 'Iceland': 'Icelandic',
 'India': 'Indian',
 'Indonesia': 'Indonesian',
 'Iran': 'Iranian',
 'Iraq': 'Iraqi',
 'Ireland': 'Irish',
 'Israel': 'Israeli',
 'Italy': 'Italian',
 'Ivory Coast': 'Ivorian',
 'Jamaica': 'Jamaican',
 'Japan': 'Japanese',
 'Jordan': 'Jordanian',
 'Kazakhstan': 'Kazakhstani',
 'Kenya': 'Kenyan',
 'Kiribati': 'Kiribati',
 'North Korea': 'North Korean',
 'South Korea': 'South Korean',
 'Kuwait': 'Kuwaiti',
 'Kyrgyzstan': 'Kyrgyzstani',
 'Laos': 'Laotian',
 'Latvia': 'Latvian',
 'Lebanon': 'Lebanese',
 'Lesotho': 'Lesotho',
 'Liberia': 'Liberian',
 'Libya': 'Libyan',
 'Liechtenstein': 'Liechtenstein',
 'Lithuania': 'Lithuanian',
 'Luxembourg': 'Luxembourg',
 'North Macedonia': 'Macedonian',
 'Madagascar': 'Malagasy',
 'Malawi': 'Malawian',
 'Malaysia': 'Malaysian',
 'Maldives': 'Maldivian',
 'Mali': 'Malian',
 'Malta': 'Maltese',
 'Marshall Islands': 'Marshallese',
 'Mauritania': 'Mauritanian',
 'Mauritius': 'Mauritian',
 'Mexico': 'Mexican',
 'Micronesia': 'Micronesian',
 'Moldova': 'Moldovan',
 'Monaco': 'Monégasque',
 'Mongolia': 'Mongolian',
 'Montenegro': 'Montenegrin',
 'Morocco': 'Moroccan',
 'Mozambique': 'Mozambican',
 'Namibia': 'Namibian',
 'Nauru': 'Nauruan',
 'Nepal': 'Nepalese',
 'Netherlands': 'Dutch',
 'New Zealand': 'New Zealand',
 'Nicaragua': 'Nicaraguan',
 'Niger': 'Nigerien',
 'Nigeria': 'Nigerian',
 'Norway': 'Norwegian',
 'Oman': 'Omani',
 'Pakistan': 'Pakistani',
 'Palau': 'Palauan',
 'Palestine': 'Palestinian',
 'Panama': 'Panamanian',
 'Papua New Guinea': 'Papua New Guinean',
 'Paraguay': 'Paraguayan',
 'Peru': 'Peruvian',
 'Philippines': 'Philippine',
 'Poland': 'Polish',
 'Portugal': 'Portuguese',
 'Puerto Rico': 'Puerto Rican',
 'Qatar': 'Qatari',
 'Romania': 'Romanian',
 'Russia': 'Russian',
 'Rwanda': 'Rwandan',
 'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
 'Saint Lucia': 'Saint Lucian',
 'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
 'Samoa': 'Samoan',
 'San Marino': 'Sammarinese',
 'São Tomé and Príncipe': 'Santomean',
 'Saudi Arabia': 'Saudi',
 'Senegal': 'Senegalese',
 'Serbia': 'Serbian',
 'Seychelles': 'Seychellois',
 'Sierra Leone': 'Sierra Leonean',
 'Singapore': 'Singaporean',
 'Slovakia': 'Slovak',
 'Slovenia': 'Slovenian',
 'Solomon Islands': 'Solomon Islands',
 'Somalia': 'Somali',
 'South Africa': 'South African',
 'South Sudan': 'South Sudanese',
 'Spain': 'Spanish',
 'Sri Lanka': 'Sri Lankan',
 'Sudan': 'Sudanese',
 'Suriname': 'Surinamese',
 'Eswatini': 'Swazi',
 'Sweden': 'Swedish',
 'Switzerland': 'Swiss',
 'Syria': 'Syrian',
 'Tajikistan': 'Tajik',
 'Tanzania': 'Tanzanian',
 'Thailand': 'Thai',
 'Timor-Leste[18]': 'Timorese',
 'Togo': 'Togolese',
 'Tokelau': 'Tokelauan',
 'Tonga': 'Tongan',
 'Trinidad and Tobago': 'Trinidad and Tobago',
 'Tunisia': 'Tunisian',
 'Turkey': 'Turkish',
 'Turkmenistan': 'Turkmen',
 'Tuvalu': 'Tuvaluan',
 'Uganda': 'Ugandan',
 'Ukraine': 'Ukrainian',
 'United Arab Emirates': 'Emirati',
 'United Kingdom': 'British',
 'United States': 'United States',
 'Uruguay': 'Uruguayan',
 'Uzbekistan': 'Uzbekistani',
 'Vanuatu': 'Vanuatuan',
 'Vatican City': 'Vatican',
 'Venezuela': 'Venezuelan',
 'Vietnam': 'Vietnamese',
 'Yemen': 'Yemeni',
 'Zambia': 'Zambian',
 'Zimbabwe': 'Zimbabwean',
 'Taiwan':'Taiwanese'}